session_status_path = 'Your session path to store the availability of login status'
base_url = 'https://www.linkedin.com/login/'
target_url = 'https://www.linkedin.com/feed/'
session_state_store_path = 'File path,which used to store the login session'
state_history_path = 'file path to store the chat_history'

CTA_type='Fresher and Experience Question about their agent building'
Length='180-220 words'
tone='fresher with a specific example from your work'
Audience='ML Engineers'