from config import session_status_path,session_state_store_path,base_url,target_url,Audience,tone,Length,CTA_type,state_history_path
from utils import load_model,content_prompt,rewritten_prompt,is_cntent_quality,agent_prompt
import json
import os
from playwright.async_api import async_playwright
from langchain.tools import tool
import asyncio
from typing import Annotated,TypedDict
from langchain_core.messages import BaseMessage
from pydantic import Field
from langchain_classic.agents import create_react_agent,AgentExecutor

class State(TypedDict):
    user_query : Annotated[str,Field('user input to create the linkedin content')]
    chat_history: Annotated[list[BaseMessage],Field('Previous chat history data')]
    content : Annotated[str,Field('Content generated by llm')]
    content_quality : Annotated[str,Field('It returns the quality of the content')]
    

async def load_chat_history(file_path):
    if os.path.exists:
        with open(file_path,'r') as file:
            history = json.load(file)
            return history
    else:
        with open(file_path,'w+') as file:
            history = json.dump([],file)
            return history

async def start_node(State):
    return {}

async def checks_session_status(State):
    if os.path.exists(session_status_path):
        with open(session_status_path,'r') as file:
            stats=file.read()
    else:
         with open(session_status_path,'w+') as file:
            stats=file.write(0)       
            
    if stats:
        return "agent_calling"
    else:
        return "manual_login"

async def manual_login(State):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()
        await page.goto(base_url)  
        try:
            await page.wait_for_url(target_url,timeout=40000)
        except Exception as e:
            raise Exception(e)    

        if page.url == target_url:
            with open(session_state_store_path,'w+') as file:
                json.dump(await context.storage_state(),file,indent=5)
                with open(session_status_path,'w') as file:
                    file.write('1')                  
        else:
            raise Exception("Please ensure that the first manual login has been successfully accomplished")       
           
        await browser.close()

async def session_login(State):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context(storage_state=session_state_store_path)
        page = await context.new_page()
        await page.goto(target_url)
        await page.get_by_role("button",name="Start a post").click()
        await page.get_by_role("textbox").fill(State["content"])
        await page.wait_for_timeout(10000)
        
async def store_chat_history(State):
    State["chat_history"].append({"User_query":State["user_query"],"AI_message":State["content"]})
    with open(state_history_path,'w+') as file:
        json.dump(State["chat_history"],file,indent=5)

async def Agent_calling(State):
    @tool
    async def create_content(TOPIC:str)->str:
        '''These tool used to create or generate the content based on the topic'''
        AUDIENCE = Audience
        TONE = tone
        LENGTH = Length
        CTA_TYPE = CTA_type
        PREVIOUS_POSTS_HISTORY=State['chat_history']
        param = {"TOPIC":TOPIC,"AUDIENCE":AUDIENCE,"TONE":TONE,"LENGTH":LENGTH,"CTA_TYPE":CTA_TYPE,"PREVIOUS_POSTS_HISTORY":PREVIOUS_POSTS_HISTORY}
        model = load_model()
        prompt = content_prompt() 
        chain = (
        prompt 
        | model 
        | (lambda message:message.content))
        response = await chain.ainvoke(param)
        State['content']=response
        return response
    @tool
    async def rewritten_content(INPUT_CONTENT:str):
            '''These tool used to improve the content quality'''
            TOPIC = State['user_query']
            AUDIENCE = Audience
            TONE = tone
            LENGTH = Length
            CTA_TYPE = CTA_type
            PREVIOUS_POSTS_HISTORY=State['chat_history']
            param = {"TOPIC":TOPIC,"AUDIENCE":AUDIENCE,"TONE":TONE,"LENGTH":LENGTH,"CTA_TYPE":CTA_TYPE,"PREVIOUS_POSTS_HISTORY":PREVIOUS_POSTS_HISTORY,"INPUT_CONTENT":INPUT_CONTENT}
            model = load_model()
            rewritten_prmpt = rewritten_prompt()
            chain = (
                rewritten_prmpt 
                | model 
                | (lambda message : message.content)) 
            State['content'] = await chain.ainvoke(param)
            return State['content']
    @tool
    async def content_quality(INPUT_CONTENT:str):
            '''These tool used to checks the quality of the content and returns quality as LOW,MEDIUM,HIGH'''
            TOPIC=State['user_query']
            model = load_model()
            prmpt = is_cntent_quality()
            chain = prmpt | model | (lambda message : message.content)
            response =await chain.ainvoke({"TOPIC":TOPIC,"INPUT_CONTENT":INPUT_CONTENT})
            quality = response.split('\n',maxsplit=1)[0].split(' ')[1]   
            State['content_quality'] = quality
            return quality
    
    model = load_model()
    tools = [create_content,rewritten_content,content_quality]
    agent_prmpt = agent_prompt()
    react_agent = create_react_agent(llm=model,tools=tools,prompt=agent_prmpt)
    agent_exec = AgentExecutor(agent=react_agent,tools=tools,verbose=True,handle_parsing_errors=True)
    response = await agent_exec.ainvoke(State)
    return response

